app: course-policy-ai
plugins:
  - serverless-offline

org: coursepolicy
service: core
frameworkVersion: '3'

custom:
  defaultStage: staging

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  stage: ${opt:stage, self:custom.defaultStage}
  httpApi:
    cors: true
  apiGateway:
    binaryMediaTypes:
      - 'application/pdf'
    metrics: true
  logs:
    restApi: true

functions:
  postPolicyWebhook:
    handler: dist/src/http/post-policy-webhook/index.handler
    events:
      - httpApi:
          path: /hook
          method: post
  getPolicy:
    handler: dist/src/http/get-policy/index.handler
    events:
      - httpApi:
          path: /policy
          method: get
    timeout: 30
  updatePolicy:
    handler: dist/src/http/update-policy/index.handler
    events:
      - httpApi:
          path: /policy
          method: put
  getGeneratedPdf:
    handler: dist/src/http/get-generated-pdf/index.handler
    events:
      - httpApi:
          path: /generated-pdf
          method: get
          throttling:
            burstLimit: 1000
            rateLimit: 500
    timeout: 180
    memorySize: 1024
    layers:
      - arn:aws:lambda:us-west-2:694509587593:layer:chromium:3
