app: course-policy-ai
plugins:
  - serverless-offline

org: coursepolicy
service: core
frameworkVersion: '3'

custom:
  defaultStage: staging

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  stage: ${opt:stage, self:custom.defaultStage}
  websocketsApiName: survey-response-api
  websocketsApiRouteSelectionExpression: $request.body.action
  websocketsDescription: Course Policy AI Survey Response Websockets
  httpApi:
    cors: true

functions:
  webhook:
    handler: dist/src/http/hook/index.handler
    events:
      - httpApi:
          path: /hook
          method: post
  response:
    handler: dist/src/http/responses/index.handler
    events:
      - httpApi:
          path: /responses
          method: get
    timeout: 30
  updatePolicy:
    handler: dist/src/http/update-policy/index.handler
    events:
      - httpApi:
          path: /policy
          method: put
