app: course-policy-ai
plugins:
  - serverless-offline

org: coursepolicy
service: core
frameworkVersion: '3'

custom:
  defaultStage: staging

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  stage: ${opt:stage, self:custom.defaultStage}
  websocketsApiName: survey-response-api
  websocketsApiRouteSelectionExpression: $request.body.action
  websocketsDescription: Course Policy AI Survey Response Websockets
  httpApi:
    cors: true

functions:
  postPolicyWebhook:
    handler: dist/src/http/post-policy-webhook/index.handler
    events:
      - httpApi:
          path: /hook
          method: post
  getPolicy:
    handler: dist/src/http/get-policy/index.handler
    events:
      - httpApi:
          path: /policy
          method: get
    timeout: 30
  updatePolicy:
    handler: dist/src/http/update-policy/index.handler
    events:
      - httpApi:
          path: /policy
          method: put
  getGeneratedPdf:
    handler: dist/src/http/get-generated-pdf/index.handler
    events:
      - httpApi:
          path: /generated-pdf
          method: get
    timeout: 300
    memorySize: 2048
