name: 'Deploy to Staging'

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AWS_REGION: us-west-2

concurrency: merge-${{ github.ref }}

permissions:
  id-token: write
  contents: read

jobs:
  staging_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile
      - run: bun run build
      - name: serverless deploy
        uses: serverless/github-action@v3.2
        with:
          args: deploy -s staging
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
